### ISSUE TITLE
[Request] - Toggling bottleneck rebuilds icon's

### ISSUE THREAD

**Issue by Nexela** [troelsbjerre/Bottleneck#12]
Currently bottleneck rebuilds icon data during on_config_changed. Would it also be possible to have it also rebuild if one toggles bottleneck off/on with the hotkey? This would be a workaround for issues like #11 (which according to the change log for that mod #11 can be closed)

**Comment by troelsbjerre** [comment]
The icon data isn't typically rebuild on_config_changed, but I can see how the messy code can make it look as if that it the case. Only if the existing data is from an earlier version of the mod, i.e., if global.version doesn't match the current version, a full rebuild is triggered. However, a full rebuild takes too much time to run in a single tick, so if the game is already running, this must be done gradually over several ticks. The current structure of the mod doesn't allow for such a gradual rebuild of the data set. I have some ideas for how to restructure the mod to allow for this, but I don't have time right now. Thus, I will leave this issue open. Issue #11 was closed by Bluebuild 0.6.4.
