### ISSUE TITLE
Some Buildings get a permanent red light

### ISSUE THREAD

**Issue by Koveras** [troelsbjerre/Bottleneck#13]
This is happening really frequent now with the latest version (0.5.0).

You can spot them easily by disabling bottleneck, they'll stay red.

http://puu.sh/sV9Xu/d545b98b86.png

removing and replacing them usually fixes it.

**Comment by Koveras** [comment]
Scratch that, sometimes lights just get stuck, this one wasn't stuck before, but now it is, and on green:
http://puu.sh/sVa94/b513889594.png

**Comment by troelsbjerre** [comment]
That is really odd. I'll downgrade the version on mods.factorio.com until I can figure out what is going on.

**Comment by Nexela** [comment]
next() is returning the next index, which you are saving to the global, but if numiter is over 39 then saved to the global, however on the next tick you are calling next() again before using the saved index.

TL:DR you are skipping indexes Also, Fixed in the upcoming pull request :)
