### ISSUE TITLE
Entity.direction based icons and Logistic chests.

### ISSUE THREAD

**Issue by Nexela** [troelsbjerre/Bottleneck#16]
Started some work on Changing the icons from create/destroy to direction based. I am still working on tweaking it some but if you want to check out what I have so far https://github.com/Nexela/Bottleneck/tree/icons.

Amazingly (because factorio). creating/destroying doesn't add as much overhead as one would think. This switch gained about a .08/tick improvement in the heavily modded test base I am using.

It uses a storage-tank entity as this is the only one I could find that supported rotation. And I couldn't find anything that supported 8x rotation after placing. So switching to high-contrast mode is something that needs some thinking on.  Also I have some ideas on more speed improvements that will be needed for logistic chest bottlenecks I am working on.

**Comment by troelsbjerre** [comment]
Great work!  I had hoped that this approach would have given a bigger improvement, but a .08/tick gain is definitely worth keeping.

The high-contrast mode should probably just be a different entity. Changing modes will then be an old-fashioned swap of all bottleneck-entities. Changing between the two modes wouldn't be a common occurrence, so it doesn't matter as much if the change-over itself isn't as optimized.

**Comment by Nexela** [comment]
> Changing between the two modes wouldn't be a common occurrence, so it doesn't matter as much if the change-over itself isn't as optimized.

My thoughts exactly! Right now I am playing around with different entities (currently looking at lamps). While I ponder more efficient ways to handle looping through the list.
