### ISSUE TITLE
0.5.0 to 0.5.1 update uses crazy amounts of RAM

### ISSUE THREAD

**Issue by troelsbjerre** [troelsbjerre/Bottleneck#17]
From https://mods.factorio.com/mods/trold/Bottleneck/discussion/6579

Something in the 0.5.0 to 0.5.1 update process causes huge amounts of RAM to be used when loading an existing save.

My existing save went from using around 4GB RAM when loaded, to using over 10GB when first loaded with the 0.5.1 version.

This was a challenge to get working - PC swapping like mad for ages, and factorio crashed due to low memory on the first attempt.

Once I managed to load the game and re-save it, it seems OK, so just something about the upgrade process I think.

It may be another mod, not bottleneck - as something similar occurred just after this when I installed another mod and loaded the save. Bottleneck did show it's 'building from scratch' message this time too, but it's possible another mod is also hooking that event, and causing the issue, but remaining silent about it's activity.

Other mods installed:
- rso-mod_2.3.0
- Bob's mods
- bobassembly_0.14.0.zip
- bobconfig_0.14.0.zip
- bobelectronics_0.14.0.zip
- bobenemies_0.14.0.zip
- bobgreenhouse_0.14.0.zip
- bobinserters_0.14.3.zip
- boblibrary_0.14.3.zip
- boblogistics_0.14.5.zip
- bobmining_0.14.0.zip
- bobmodules_0.14.1.zip
- bobores_0.14.0.zip
- bobplates_0.14.0.zip
- bobpower_0.14.0.zip
- bobrevamp_0.14.1.zip
- bobtech_0.14.0.zip
- bobvehicleequipment_0.14.2.zip
- bobwarfare_0.14.2.zip
- Auto_Deploy_Destroyers_0.1.5
- RadarGridGuide_0.1.3
- add-loader_0.0.8
- compoundsplitters_0.2.8
- Inventory Sensor_1.1.5
- nixie-tubes_0.3.10
- personal-roboport-switch_0.1.4
- ScoreExtended_1.0.22
- UsefulMapColors_1.1.5
- Warehousing_0.0.11

Here's the save game and set of mods that caused me the RAM problems.

http://www.jonatkins.com/factorio/bugs/mod-upgrade-ram-0.14/

**Comment by troelsbjerre** [comment]
I didn't have time to look at it properly, but the behavior described in the bug definitely shows up. Removing the Bottleneck mod, or keeping it at 0.5.0 avoids the problem.

**Comment by Nexela** [comment]
Ouch, Any time the rebuild is called on a "hugely decorated map" this will happen. It is related to the speed change on rebuilding icons and possibly Factorio not garbage collecting correctly afterwards.
I didn't take this into consideration (the big test worlds I have been using have all decorations removed)

His map has almost 6 million decorative entities.........
After upgrading - 9GB-11GB for the world
After taking a save after upgrading Bottleneck and reloading the map is only using 3GB
After Destroying all decorative and saving/ loading Ram usage went to Under 2GB, and save file size went from 80MB to 54MB.

For now I recommend uninstalling bottleneck, install mod https://mods.factorio.com/mods/orzelek/undecorator 
Load the world (it might shoot up to about 10GB again).  After it loads Save and reinstall bottleneck.

I'll shoot over a pull request that will fix this. The change to direction based doesn't have this problem but unfortunately that isn't ready to shoot over yet.

**Comment by troelsbjerre** [comment]
You don't even need to uninstall Bottleneck before installing unDecorator. Bottleneck is robust enough to handle having its indicator lights destroyed by another mod.

**Comment by Nexela** [comment]
Sorry, should have clarified it some.  uninstalling bottleneck before running undecorater was suggested due to the amount of decoratives and only applies to .51 version.  If bottleneck.51 runs before undecorater there is a chance the ram usage will double again and be un-loadedable.  This won't be a problem with .52 :)

**Comment by troelsbjerre** [comment]
Oh, right. If Bottleneck's rebuild is triggered before unDecorator's initial scan, then the memory spike is back, and my laptop sits in the corner crying.
