### ISSUE TITLE
my bottlenecks turned into vehicles

### ISSUE THREAD

**Issue by Shilkwurm** [troelsbjerre/Bottleneck#20]
i can get inside of the little balls and they are being moved around by transport belts. They also appear on the map as vehicles. The latest update broke them somehow.

**Comment by Nexela** [comment]
Looking into this now.

As to them being moved by transport belts I am not sure how that is happening. do you have a screenshot?

**Comment by Nexela** [comment]
So far I have fixed the vehicle issue.
Still need to figure out if I can remove the map icon.

Also reproduced the sliding bottlenecks bug.  I am going to spend a few more minutes on this and if I can't figure out how to solve it I will have to revert back the simple icon swapping I have in an earlier commit. 

@troelsbjerre Probably should remove the latest version from mod portal until I get get a fix pushed over to you.
