### ISSUE TITLE
Separate Forces / Multiplayer is totally broken when comes to toggle.

### ISSUE THREAD

**Issue by KaneHart** [troelsbjerre/Bottleneck#24]
It seems this mod only toggles globally in multiplayer and must be the admin. So sadly if I want it on everyone else has to have it on and vise versa. It should be per user not the entire server or at least per force so if people separate teams their not effected.

Should also not require admin permissions.

**Comment by troelsbjerre** [comment]
I agree that individual control would be way better, but I have no idea how to make LuaEntities visible to only a subset of the players. I only know how to make everybody see the same view of the map. Feel free to contribute a solution: https://forums.factorio.com/viewtopic.php?f=25&t=42309
And no, it is not "Totally broken". One person can toggle for everyone, and the mod correctly does this.

**Comment by troelsbjerre** [comment]
According to Klonan in above forum discussion, "It cannot be done at this time".
