### ISSUE TITLE
Bottleneck Hotkey

### ISSUE THREAD

**Issue by Nexela** [troelsbjerre/Bottleneck#29]
People and their hotkeys! :)

Since the enable switch isn't tied directly to the setting it might be possible to add an override that allows the use of a hotkey. With the side effect being that the main enable/disable setting won't always show the current status.

I will look in this over the weekend

**Comment by troelsbjerre** [comment]
I've decided to simply remove the menu item, and reintroduce the hotkey. It's not optimal, but I think it's a better solution that to have an inconsistent state.

Fixed by 0.8.1
