### ISSUE TITLE
Confirmed change to Graphics Variants

### ISSUE THREAD

**Issue by Nexela** [troelsbjerre/Bottleneck#30]
https://forums.factorio.com/viewtopic.php?f=7&t=46762&p=268769#p268769

If this in indeed a bug it will break icons. Something to keep an eye on!

**Comment by Nexela** [comment]
Confirmed bug fixed for next release, Fix is easy just remove the [] index from LIGHTS

**Comment by troelsbjerre** [comment]
Isn't Rseding saying that it will be fixed for 0.15.10?

**Comment by Nexela** [comment]
Yes, Which means we will need to update the LIGHTS variable to start at 1 and not 0

**Comment by troelsbjerre** [comment]
Fixed by 0.7.1
