### ISSUE TITLE
Missing locale, interface not updated

### ISSUE THREAD

**Issue by Nexela** [troelsbjerre/Bottleneck#35]
Missing the hotkey locale, interface for enabled status not updated annnnnnd hotkey is incorrect, should be 
`SHIFT + ALT + L`

**Comment by Nexela** [comment]
Also please set consuming to none :)

**Comment by troelsbjerre** [comment]
Will do, but why would you want SHIFT+ALT+L? Right now, it works by simply pressing shift and alt and nothing else.

**Comment by Nexela** [comment]
Actually showed up as not bound for me, I figured a typo.  Also wouldn't setting it to shift-alt make it toggle when doing other keybinds that have shift+alt?

**Comment by troelsbjerre** [comment]
Nothing like platform dependence ;)

Yeah, you're right, it would toggle with other shift+alt key binding.

**Comment by troelsbjerre** [comment]
Fixed in 0.8.3
