### ISSUE TITLE
Light colours are saved, but not used after loading a saved game

### ISSUE THREAD

**Issue by pjf** [troelsbjerre/Bottleneck#36]
Thank you *so* much for Bottleneck; it's an awesome mod and I use it for all my factorio games. I've been loving the new configurable light styles, but unfortunately I'm having trouble getting them to remain between saves.

**What happens:** Colours can be changed and work great in the current playthrough. However if Factorio is restarted and the game reloaded, the saved settings *do not* take effect, and the defaults are used. However the settings *can* be seen when navigating to `options -> mods` after the game has been loaded.

**What was expected to happen:** Changes to bottleneck colours should be applied after loading a game.

**Workaround:** Changing the settings to another colour, applying those changes, and then setting them back to the desired colour works.

My particulars: I'm red/green colour-blind, and so I use no display for running, red for stopped, and blue for full.

Versions: Bottleneck 0.8.3 under Ubuntu Linux 16.04 and Factorio 0.15.

Thank you again for a fabulous mod!

~ Paul

**Comment by troelsbjerre** [comment]
Ah, yes. I see why this would happen (on any platform actually). I forgot that the default values are simply written in control.lua instead of fetching them from the settings. It's an easy fix that I'll probably have time for tonight.

**Comment by pjf** [comment]
You rock! Thanks for the quick response, and for an absolutely fantastic mod!

**Comment by troelsbjerre** [comment]
Fixed by 0.8.4. Thank you for the bug report :)

**Comment by pjf** [comment]
You're wonderful! Thank you so much for this. Shall be playing with the updated bottleneck tonight!
