### ISSUE TITLE
Default values are wrong for new games

### ISSUE THREAD

**Issue by troelsbjerre** [troelsbjerre/Bottleneck#37]
For some reason, factorio ignores the default_value given in settings.lua, so all states default to green for new games. Manually changing the settings works fine, and it survives saving.

**Comment by Nexela** [comment]
It shouldn't ignore the defaults.  You probably had? them saved on your end as not defaults in which case they would be your defaults

**Comment by troelsbjerre** [comment]
Hmm... You are right. The problem is limited to the development machine.
