### ISSUE TITLE
Crash on migration in v0.2.5

### ISSUE THREAD

**Issue by doktorstick** [troelsbjerre/Bottleneck#4]
On Factorio 0.14.1, I was using a version of Bottleneck 0.2.4. I updated Bottleneck to 0.2.5 and when I load my map, which was started anew on Factorio 0.14.1, I get the error:
```lua
Error while running event on_tick (ID 0)
position not specified.
stack traceback:
__Bottleneck__/control.lua:135: in function `change_signal`
__Bottleneck__/control.lua:167: in function 'update'
__Bottleneck__/control.lua:116: in function <__Bottleneck__/control.lua:94>
```
(I typed all that in, so there may be typos by the line numbers are correct.)

**Comment by troelsbjerre** [comment]
Yes, I forgot to update the version tag in the save file, so it doesn't refresh the data before trying to use it. However, there is no reason to update the base dependency in info.json. I will push this to mods.factorio.com later today. Temporary work around is to disable the mod, load the game, save the game, and re-enable the mod. This will refresh the data.

**Comment by doktorstick** [comment]
Here's the [forum post](https://forums.factorio.com/viewtopic.php?f=3&t=31574&start=10#p199133) from koverex that I mentioned in my pull request--the `base` dependency shouldn't be there, anymore.

**Comment by troelsbjerre** [comment]
Thanks. I forgot to check for pull requests, and had already incorporated your change into v0.3.0.
