### ISSUE TITLE
Incorrect state for Chemical plant if output is full

### ISSUE THREAD

**Issue by ochristi** [troelsbjerre/Bottleneck#40]
I noticed the machine state to be detected incorrectly, when the output of a fluid box is full and the machine is halted.
I suspect an error in function `has_fluid_output_available`, maybe the fix of #38 broke it or the behavior changed.

I will investigate this these days.

**Comment by troelsbjerre** [comment]
That would be great. I am afraid I don't have time to look into it right now.
