### ISSUE TITLE
Shows output-blocked if input is similar to output

### ISSUE THREAD

**Issue by Wolvereness** [troelsbjerre/Bottleneck#43]
The display is output-blocked if there is a partial input of the same type of output.

In particular, this is with coolant in `seablock` cooling towers. The input liquid is at a high temperature, while the output is a lower temperature. When it has some partial amount of the input, the display shows it is output-blocked, despite outputs being empty.

**Comment by troelsbjerre** [comment]
That makes sense. I can't see an easy fix to this, since fluid isn't separated into input and output the way that items are; there is only the entry.fluidbox for both of them. I'll have to think about this one.

**Comment by troelsbjerre** [comment]
This issue is no longer relevant, with the new update logic.
