### ISSUE TITLE
Not listening to script_raised_revive

### ISSUE THREAD

**Issue by Klonan** [troelsbjerre/Bottleneck#49]
If another mod/script calls revive on an entity ghost, the bottleneck icon thing is not applied to it.

Bottleneck mod should listen for the `script_raised_revive` event:
https://lua-api.factorio.com/latest/events.html#script_raised_revive

And apply the bottleneck logic to the new entity.

**Comment by troelsbjerre** [comment]
Fixed in 0.10.1
