### ISSUE TITLE
Coal Liquifaction Dot Error

### ISSUE THREAD

**Issue by adrianvanderwal** [troelsbjerre/Bottleneck#55]
![image](https://user-images.githubusercontent.com/6479661/55776014-e21f2c00-5acd-11e9-8778-8256f29a764b.png)

As you can see, the dot is coloured yellow - the "output blocked" state, where it should be red - the ingredient shortage.

I believe it has something to do with the fact that coal liquifaction uses heavy oil for both input and output ingredients.

**Comment by troelsbjerre** [comment]
Thank you for the report. This bug will be fixed by the 0.17-api update. If you want a preview, check out the feat-0.17api branch.

**Comment by adrianvanderwal** [comment]
Awesome.
Thanks for the great mod!
