### ISSUE TITLE
CFAN considers this compatible with 0.13.x but Factorio doesn't

### ISSUE THREAD

**Issue by Sacro** [troelsbjerre/Bottleneck#6]
Not sure if this an issue on your side or on CFAN but I just hit update all and then it wouldn't work on my save!

**Comment by troelsbjerre** [comment]
I don't know how CFAN determines compatibility, but I think I've set everything correctly in info.json. The mod is "compatible" with 0.13.x simply by using a different info.json. To my knowledge, there is no way for a mod to state that it works with both 0.13 and 0.14.

**Comment by Nexela** [comment]
This is a CFAN bug, and sounds pretty much like the same bug present in factorio 13.18 with downloading .14 mods from the in game portal
