### ISSUE TITLE
Customize RGB values?

### ISSUE THREAD

**Issue by birkenfeld** [troelsbjerre/Bottleneck#66]
Hi,

first, thanks for the useful mod.  For me, the distinction between yellow and green is a bit too weak; I'd prefer the yellow to have a more orange tone.  (I seem to remember it differently, but that was some versions ago and with a different monitor.)

The mod is already very configurable, so would it be possible to make the RGB values for the different preselected colors (red/yellow/green/...) editable?

Thanks!

**Comment by troelsbjerre** [comment]
It wouldn't be difficult to add, but it significantly increases the number of options to set. I'm not a big fan of forcing the player to edit each rgb value individually for each possible signal, but I don't have a good suggestion for fixing it in UI.
In the meantime, you could just work around the issue by editing line 57 of the data.lua file.

**Comment by birkenfeld** [comment]
What I intended to propose isn't to customize the color for each signal, but to customize the RGB values of the colors you can already select, e.g change "red" to be `#FF3300` instead of `#FF0000`.

**Comment by troelsbjerre** [comment]
What about the updated colors of 0.11.3?

**Comment by birkenfeld** [comment]
Yes, these work nice for me. Thanks!
