### ISSUE TITLE
Roang-zero1/factorio-create-release-action failing

### ISSUE THREAD

**Issue by troelsbjerre** [troelsbjerre/Bottleneck#73]
ERROR: Changelog was not compiled.

Is it required that the changelog be compiled with the factorio-changelog-creator?

**Comment by Roang-zero1** [comment]
That could use a better error message...
Basically it just looks for the version number in the changelog.txt (see https://github.com/Roang-zero1/factorio-create-release-action/blob/master/entrypoint.sh#L33-L36).
If it does not find it this leads to this error.
