### ISSUE TITLE
Compensate for new electric drill graphics having status light built in.

### ISSUE THREAD

**Issue by troelsbjerre** [troelsbjerre/Bottleneck#79]
https://www.reddit.com/r/factorio/comments/h0efru/til_the_new_miner_model_has_status_lights/

Should the Bottleneck signals be removed from electric mining drills, or are there states that still require separate signalling?

**Comment by lstor** [comment]
I can't think of any states that require separate signalling. The built-in status lights have states for active, blocked and ore patch empty. In addition, the status light is turned off when there's no power.

![image](https://user-images.githubusercontent.com/613821/86094236-882ecb80-bab0-11ea-8c69-8260bfb33b2a.png)

**Comment by troelsbjerre** [comment]
Yeah, it seems like removing the indicator was not universally popular, to say the least. I will reopen the issue, as there needs to be an option for selecting which types of machines should have a light or not. Unfortunately, I haven't had the time to do this properly yet; according to my steam profile, I have only had time for a combined 4 hours of games over the past three months :(

**Comment by Cisien** [comment]
I personally find it difficult to see what the state of the drills are, and i'm not colorblind. The colors on the stock model very easily blend into the background noise of the game

**Comment by troelsbjerre** [comment]
I agree that it was a mistake to disable this light in general. There needs to be a more fine grained control for enabling and disabling for each individual type of machine, which isn't a quick fix. I haven't had time for anything factorio related for several month, so the work around for the time being is just to install the previous version of the mod, which is available on the mod portal.

**Comment by lethargi** [comment]
I tried reverting the changes by lstor manually. it didnt work. But if I install the previous version ( 0.11.3), it works. Can someone explain why this?

My steps:

1. unzip 0.11.4 mod files into my mod folder
2. modify the `control.lua` file to remove [this](https://github.com/troelsbjerre/Bottleneck/blob/802977ea893646b9cbc74d76f70c9f0cc2433595/control.lua#L54) line
3. restart Factorio
4. check if electric miners have signal -> they dont
5. Retry by donwloading and installing 0.11.3 -> signals show up

**Comment by troelsbjerre** [comment]
The issue is that you need to trigger a full recomputation, which only happens automatically when the version number changes.

**Comment by troelsbjerre** [comment]
I finally had some time to play, and I rolled back the change that disabled the lights on the mining drills. It is not really a satisfying solution, as the mod should allow the player much more fine grained control over which entities have lights.
