### ISSUE TITLE
REQ admin switch for bottleneck toggle

### ISSUE THREAD

**Issue by Nexela** [troelsbjerre/Bottleneck#9]
In big MP games bottleneck can be script intensive. Thankfully it can be disabled/enabled with a hotkey :)

I propose this goes one step further and limit the toggling to .admin. Single player is always admin and in mp admins are admins. This would limit the people who can turn the icons on and off.

if player.admin toggle on/off in hotkey function

**Comment by troelsbjerre** [comment]
Good point. I'll add it to the next release.

**Comment by CoopernetsUni** [comment]
Just as a quick aside, I think that you just need to add the admin:true to the json. This was only after a cursory look though :)

**Comment by troelsbjerre** [comment]
A think the "admin:true" approach is only scheduled for 0.15, if I am reading this correctly: https://forums.factorio.com/viewtopic.php?f=34&t=32890#p207275

**Comment by troelsbjerre** [comment]
I've added an explicit test for admin rights, and it displays an error message, if you don't have admin rights. Furthermore, I've changed the behavior when toggling the lights off: they are now removed at the same rate as updates, instead of all at once.
